spring:
  application:
    name: backend
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/cashcard_family
    username: cashcard
    password: cashcard
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics